version: '3.5'
services:
  mediawiki:
    image: mediawiki
    restart: always
    ports:
      - 8082:80
    links:
      - database
    volumes:
      - images:/var/www/html/images
      - ./LocalSettings_1.php:/var/www/html/LocalSettings.php
  database:
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: ubuntu
      MYSQL_PASSWORD: 12345
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - db:/var/lib/mysql

volumes:
  images:
  db:
